### ISSUE TITLE
Error when ejecting

### ISSUE THREAD

**Issue by EricForgy** [creativetimofficial/ct-material-kit-pro-react#15]
Hi. I am a noob, so this is likely user error. This seems like an awesome template 🙌  I was hoping to add an Express server and some API endpoints. If I can do that without ejecting, I'll give it a try (and appreciate any pointers), but maybe good to record this issue.

# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

```
>npm run eject
>npm start
Compiled successfully!

You can now view material-kit-pro-react in the browser.

  Local:            http://localhost:3000/
  On Your Network:  http://xxx.xxx.x.xx:3000/

Note that the development build is not optimized.
To create a production build, use npm build.
```

# Current Behavior

```
>npm run eject
>npm start
Failed to compile.

./src/components/Typography/Muted.jsx
  Line 10:  'children' is missing in props validation  react/prop-types

Search for the keywords to learn more about each error.
```

# Failure Information (for bugs)

## Steps to Reproduce

1. Download, unzip and navigate to package folder
2. npm install
3. npm run eject
4. npm start

## Context

* Device: Dell XPS 15
* Operating System: Windows 10
* Browser and Version: Chrome Version 69.0.3497.100 (Official Build) (64-bit)

## Failure Logs

Failed to compile.

./src/components/Typography/Muted.jsx
  Line 10:  'children' is missing in props validation  react/prop-types

Search for the keywords to learn more about each error.

**Comment by einazare** [comment]
Hello there @EricForgy ,

Thank you for your interest in using our products.
Here at Creative-Tim we do not work with yarn, and I can't really get any help from any of my colleagues, that is the main reason in our live docs we say to use `npm`.
This being said, I will try my best to help you.
First of all, could you please tell me what `yarn eject` does?
From the error you are showing me, the problem would be that inside our `Muted` (`src/components/Typography/Muted.jsx`) component we haven't added the `children` prop inside our props object (see lines 18-20 inside this component).
But I am a bit confused since we haven't type checked the children prop in any of our components, and the confusion is, why the error is only for the `Muted` component, and not for all components?
If you add the children prop inside our `propTypes` object, is this till an issue?

Best,
Manu

**Comment by EricForgy** [comment]
Hi @EINazare ,

Thank you getting back to me. Like I said, I'm a noob and didn't think there was a significant different between `yarn` and `npm`. It seems fine using `npm` so that works for me. Thank you again 😊

**Comment by EricForgy** [comment]
Oops. I take it back. I thought it worked with npm, but I get the same error:

```
Failed to compile
./src/components/Typography/Warning.jsx
  Line 10:  'children' is missing in props validation  react/prop-types

Search for the keywords to learn more about each error.
```

I'll go ahead and edit the first post to use `npm` instead of `yarn` since it is the same error (pretty much).

**Comment by einazare** [comment]
Hello again @EricForgy ,

Are you using TypeScript?

Best,
Manu

**Comment by EricForgy** [comment]
HI @EINazare ,

I'd like to use TypeScript and I'm using TypeScript for other projects, but this issue appears before I have a chance to introduce TypeScript. I'm pretty sure it happens with a fresh download of Material Kit. Do you not see the same thing?

This issue is just FYI as I found a way to do what I wanted without ejecting. Feel free to close it if you like and you're not seeing the same thing. It could just be a problem on my end.

**Comment by Treverix** [comment]
Knowing that this issue is pretty old, but this may shed some light on the issue. `eject` is defined in the `package.json` file which is shipped with the project and `npm run eject` does the normal `eject` of a project which has been created with `react-scripts`.
The problem that seems to prevent from ejecting is a small issue on that `Warning.js` file. It defines propTypes but that should included the `children` property too, which is used by that component.

This code should fix it, you could use it for the next release and each user can just update the file, if it blocks from ejecting. 

```
Warning.propTypes = {
  classes: PropTypes.object.isRequired,
  children: PropTypes.object
};
```

Cheers!

**Comment by nubz** [comment]
I too had to npm eject (to enable Basic Auth on the dev server) - there were multiple compile errors throughout the codebase once ejected - most of them are esLint and prettier code style errors - it would seem ejecting can subject the code build to stricter standards. Most of them are easy, if a little laborious, to fix and relate mainly to missing prop declarations and the use of string refs.

**Comment by einazare** [comment]
Hello there @nubz ,

Thank you for your interest in working with our products and thank you for telling us about this.
On our next update we'll try to solve all the eslint issues.

Best,
Manu
