### ISSUE TITLE
[enhancement] Auto close dropdown submenus

### ISSUE THREAD

**Issue by ghost** [creativetimofficial/ct-material-kit-pro-react#20]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

When using a multilevel dropdown, submenus could be closed when you close the dropdown

# Current Behavior

When you close a dropdown that has a submenu open and open the menu again, that submenu still open... I think that it should close all levels or at least give the option to do so with some prop

# Failure Information (for bugs)

NA

## Steps to Reproduce

NA

## Context

NA

* Device: PC
* Operating System: Windows 10 Home
* Browser and Version: Mozilla Firefox 63.0.1

## Failure Logs

NA

**Comment by einazare** [comment]
Hello there @guilhermeoholz ,

Thank you for your interest in working with our products.
I've struggled a bit to create those MultiLevelDropdowns the way they are, and couldn't figure out a way to make them close on parent close -> since they are kind of two separate components, they are not really linked in any way.
In your comment you say

> When using a multilevel dropdown, submenus **could be closed** when you close the dropdown

> could be closed

I would really like to know how they could be closed if you've found the way of doing so.
Since this is a PRO paid product, we cannot share the code here from it, but you can send me the code to revise it at my email here: [manu@creative-tim.com](mailto:manu@creative-tim.com) . 
If it is working as expected with no visual and / or code bugs, then we are going to add it in our next update.

Best,
Manu

**Comment by guilhermeoholz** [comment]
Thanks for the reply, Manu

We've bought the bundle on the Halloween sale and we been using the
Material Kit Pro React for about a week now. I've done some changes on a
few components, like add a autoHideDuration prop to the snackbars, add a
fixed width to the dropdown menu, etc, so they work better according to our
needs.
If you're interested in see these changes, let me know! I'll try something
with the dropdown and if I found some solution, I let you know!

Best,
Guilherme Holz

Em sex, 2 de nov de 2018 às 03:43, Nazare Emanuel-Ioan <
notifications@github.com> escreveu:
