### ISSUE TITLE
Use with Nextjs

### ISSUE THREAD

**Issue by llwor94** [creativetimofficial/ct-material-kit-pro-react#31]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Trying to get the components working in a nextjs SSR project.

# Current Behavior

The first page to render displays the styles perfectly- then any other page the styles are wonky and completely bizarre looking.

# Failure Information (for bugs)

_document.js
![document](https://user-images.githubusercontent.com/35212660/52758962-10492980-2fbf-11e9-8e00-2109b35829ba.png)
_app.js
![app](https://user-images.githubusercontent.com/35212660/52758970-1a6b2800-2fbf-11e9-9335-52e5fbd63952.png)

**Comment by einazare** [comment]
Hello there, @llwor94 ,

Thank you for your interest in working with our product.
At the moment we haven't worked with NextJS (to be honest, we haven't quite worked with React & back-end technologies). I am not sure what assistance I can give you.
I've spoken with the board and since there were many requests on integrating our products with NextJs we'll invest some money in learning NextJs, but right now, since we are stuck on some other projects we do not have the time to learn something new.
At the moment, since there were many other clients of ours that wanted to integrate our products with Firebase and an API, we've already invested quite some money in learning how to do the two mentioned technologies. While learning these technologies we're also working on new products as well.
For the next 2-4 months, we're stuck on launching new products and learning the above technologies. After that, we'll start and create a learning plan for NextJs which will end in an Tutorial like these ones here:

1. https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
2. https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
3. https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx
4. https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a

I'll leave this issue opened, and maybe someone from our comunity will come to your help.

Also, altought I do not know - and none of my colleagues at Creative-Tim - how to work with NextJs, or what is really does, if you want, you can send me your project here: manu@creative-tim.com . And on monday (18th February) I'll take a look at it and see if there is something I can do to help. This will require you to give me a little more detailed overview of your project - how to start it, how to install it (ATTENTION: we only use npm, and yarn not at all), how to navigate through your routes, where the issue appears, what link I should press to render the wrong page etc. Also, I will require you to give me your order id you've got from us upon purchase.

Best,
Manu
