### ISSUE TITLE
 Best Way to Integrate this with my Meteor App

### ISSUE THREAD

**Issue by kholisrag** [creativetimofficial/ct-material-kit-pro-react#35]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I want to use this template to integrate it with my meteor app, 

# Current Behavior

I don't know the best way to integrate it with my meteor app

# Failure Information (for bugs)

I just want to ask about detailed tutorial to integrate it with my meteor app

## Context

I'm using Latest Meteor Version 1.8.x

* Device: darwin
* Operating System: macOS
* Browser and Version: Google Chrome 73

**Comment by einazare** [comment]
Hello there, @petrukngantuk ,

Thank you for your interest in working with our products.
Sorry for this late response, since I am a Christian I've had some free days for the Easter Holiday:

- https://www.calendar-12.com/holidays/easter
- https://www.officeholidays.com/religious/orthodox/orthodox_easter.php

At the moment we haven't worked with Meteor, and to be honest do not really know how it works, what it does. I do not know how I can help you.
I've added this to my list of tutorials.

All the best,
Manu
