### ISSUE TITLE
Convert a file to Base64 using ImageUpload

### ISSUE THREAD

**Issue by Crael94** [creativetimofficial/ct-material-kit-pro-react#37]
# Expected Behavior

Hello, I wanted to use the `ImageUpload` ([link to the docs](https://demos.creative-tim.com/material-kit-pro-react/?_ga=2.176416546.66233291.1556091238-606021383.1540553838#/documentation/upload)) component to upload files like pictures or PDF.
I would like to convert these file into Base64 to send them to my api. That's for I have two questions:

1. How can I call properly `handleSubmit()` 
2. How can I convert my file into Base64 string ?

# Current Behavior
When I click on the "upload button" and select a file I can `console.log` the `this.state.file` in the render function of the component file `src/components/CustomUpload/ImageUpload.jsx`.

That is the result in my browser logs: 
<img width="470" alt="Capture d’écran 2019-04-29 à 15 40 51" src="https://user-images.githubusercontent.com/25455978/56900062-3b5af980-6a95-11e9-8d69-914dc71b0f14.png">

In the component file inside the `handleSubmit()`, they tell us (line 35)

  ```
    // this.state.file is the file/image uploaded
    // in this function you can save the image (this.state.file) on form submit
    // you have to call it yourself
```
I tried to call `handleSubmit()` in the `handleClick()` (line 40) function but  it doesn't work fine because `handleSubmit()` do not wait the selected file in the file browser.

* Device: Macbook Pro 2018 (touch bar)
* Operating System: macOS Mojave Version 10.14.4
* Browser and Version: Chrome Version 73.0.3683.103 (Build officiel) (64 bits)

**Comment by einazare** [comment]
Hello there, @Crael94 ,

Thank you for your interest in working with our products.
Sorry for this late response, since I am a Christian I've had some free days for the Easter Holiday:

- https://www.calendar-12.com/holidays/easter
- https://www.officeholidays.com/religious/orthodox/orthodox_easter.php

At the moment we haven't worked with back-end logic, and we do not really know how you would submit something to your back-end. This being said, without knowing I believe that the `handleSubmit` should be called inside the `reader.onloadend` function. Also, you should change the code inside the `handleSubmit` function - it is a blank function, it doesn't do anything. And, since this is React that we are talking about, most definitely this function should have an Ajax call to a REST API. But once again, we are just front-end developers. There may be more to this.

Hope this will help.

All the best,
Manu

**Comment by Crael94** [comment]
Hello @EINazare,

Thank you for this answer, I found a solution, here is my code:

**imageUpload.jsx**

```
handleImageChange(e) {
    e.preventDefault();
    let file = e.target.files[0];
    let reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onloadend = () => {
      this.setState({
        file: file,
        base64: reader.result
      });
      this.handleSubmit()
    };
  }
```

In this function the issue was `reader.readAsDataURL(file)` (line 33). It has to be before the `onloadend`. Then the `reader.result` is the a base64 string of the file.

I hope I  can help someone !

**Comment by einazare** [comment]
Hello again, @Crael94 ,

I will leave this issue open. As you've said it, maybe it will help someone.

All the best,
Manu

**Comment by alcalcides** [comment]
Thank you so much for your help

**Comment by piedrucci** [comment]
@Crael94 this is great!, it works for me. very helpful.. thanks so much
