### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by dohomi** [creativetimofficial/ct-material-kit-pro-react#50]
### What is your enhancement?
Hello,

I am interested in your react themes based on material-ui component framework. As I strictly have to use Typescript I would like to know if you are planning to support this in the upcoming releases. 

Thanks
Dominic

**Comment by einazare** [comment]
Hello there, @dohomi ,

Thank you for your interest in working with our products.
At the moment we do not have a timeline for this.

Best,
Manu

**Comment by phal0r** [comment]
We have an App built with React + Typescript. Some components of the Material Pro Kit are unusable in this constellation, i.e. CustomButton component, which uses ReactForwardRef to enhance the Material UI Button. This gives us an Typescript Error. Can you provide a way to make it compatible with Typescript projects, even if it is not created in Typescript itself?

Thanks in Advance!
Martin

**Comment by einazare** [comment]
Hello there, @phal0r ,

At the moment none of our React products make use of TypeScript, and this is mostly due to the fact that none of my colleagues, nor me, have worked with TypeScript.
Are any of these links helpful to you:

- https://stackoverflow.com/questions/37505904/convert-jsx-to-tsx
- https://www.samatkins.me/post/converting-react-app-typescript/

Best,
Manu

**Comment by phal0r** [comment]
@EINazare 
Thanks for the links. I will check, if it solves my problem and report my findings :)

**Comment by phal0r** [comment]
Unfortunately, this doesn't solve my problems. I think, that there are (currently) 3 main problems:
- ReactForwardRef 
- all styles, that have enums, i.e. `position: absolute`
- styles, that are defined as numbers, but are used as strings in react kit, i.e. `zIndex`

This needs to be properly set, when defining styles. Both problems cannot be solved by the suggestions from your link.

Since Material UI supports Typescript, the react kit should at least have basic support, so it can be used in Typescript projects.

**Comment by dohomi** [comment]
@EINazare did you close the issue saying that you will not consider TypeScript? Just asking because I am still watching this repo. Thanks

**Comment by einazare** [comment]
Hello there, fellow developers,

As of the moment, we are not going to support TypeScript in any of our React products, that is why I've been asked to closed the issue.
We plan that by the end of next year to start adding to our marketplace React & TypeScript products.

Best,
Manu

**Comment by benjamin-tong** [comment]
Hi there,

I am very interested in using the product. However, after taking a long time I just know that Typescript is not supported which is so surprised and seems a bit ridiculous as such a great product does not have enough technical support and I have to give up using it because of this reason.

Typescript is one of many ways to achieve the best practice and quite a lot of people using React with Typescript. I think the Material kit team really needs to push this as this problem will ruin the motivation of user to use and buy your product and I am obviously one of them.

Have a great day and stay safe.

**Comment by jhagberg** [comment]
Any update on the Typescript support for the pro version?

**Comment by einazare** [comment]
> Hello there, fellow developers,
> 
> As of the moment, we are not going to support TypeScript in any of our React products, that is why I've been asked to closed the issue.
> We plan that by the end of next year to start adding to our marketplace React & TypeScript products.
> 
> Best,
> Manu

No updates, still the same as my last comment

**Comment by eleventhaus** [comment]
> We plan that by the end of next year to start adding to our marketplace React & TypeScript products.
> 
> Best,
> Manu

Any update?

**Comment by benjamin-tong** [comment]
I suggest you stop giving any hope on this based on his response. I had converted the free version to TypeScript myself. I really appreciate that the team created and provided the Material Kit React for free, yet it will be the team's loss if Material Kit React does not support TypeScript in the pro version - which is their decision and I can only pay my respect to them. You can fork my public [repo](https://github.com/bentong95923/material-kit-react-typescript) if needed. Hope this help.

> > We plan that by the end of next year to start adding to our marketplace React & TypeScript products.
> > Best,
> > Manu
> 
> Any update?
