### ISSUE TITLE
Not able to load in Samsung Smart TV Web browser

### ISSUE THREAD

**Issue by CocoTerawe** [creativetimofficial/ct-material-kit-pro-react#54]
Not able to load the theme in Samsung Smart TV Web browser, it was blank.

**Comment by einazare** [comment]
Hello there, @CocoTerawe ,

Thank you for your interest in working with our products.
First of all, I will close this thread, since it is not in accordance with our rules:
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/material-kit-pro-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->

```
As you can see, you were supposed to follow some steps to open a new issue.
Next, I've tested the product on a Samsung Smart TV and everything worked perfectly, check the bellow image:
![72462991_456905101615402_3168944982589440000_n](https://user-images.githubusercontent.com/26245512/67072863-7e697000-f18e-11e9-8891-de5a8b86cfe5.jpg)

Best,
Manu
