### ISSUE TITLE
[Feature request] pop-up on image click

### ISSUE THREAD

**Issue by sakhmedbayev** [creativetimofficial/ct-material-kit-pro-react#59]
### Version
1.8.0
### Reproduction link
https://demos.creative-tim.com/material-kit-pro-react/#/blog-post
### Operating System
iOS
### Device
mac
### Browser & Version
latest
### Steps to reproduce
It would be great to have images to show in a pop-up/modal window on the user's click.
### What is expected?
An image to display in a modal window on the user's interaction
### What is actually happening?
nothing

---

**Comment by einazare** [comment]
Hello there, @sakhmedbayev ,

We have this page about modals: https://demos.creative-tim.com/material-kit-pro-react/#/documentation/modals
Instead of applying the onClick on the button, you would put it on your image, or on your anchor element from the image.
Also, instead of the content from our sample modals, you would put the image that you want to show.

Best,
Manu

**Comment by sakhmedbayev** [comment]
> Hello there, @sakhmedbayev ,
> 
> We have this page about modals: https://demos.creative-tim.com/material-kit-pro-react/#/documentation/modals
> Instead of applying the onClick on the button, you would put it on your image, or on your anchor element from the image.
> Also, instead of the content from our sample modals, you would put the image that you want to show.
> 
> Best,
> Manu

@EINazare :-) I know that I can do that. My request is to include such a feature in the kit

**Comment by einazare** [comment]
Hello again, @sakhmedbayev ,

We'll add this to our live docs.

Best,
Manu
