### ISSUE TITLE
[Bug] Modals move other UI elements when opening and closing

### ISSUE THREAD

**Issue by rickstaa** [creativetimofficial/ct-material-kit-pro-react#81]
### Version
1.9.0
### Reproduction link
https://demos.creative-tim.com/material-kit-pro-react/#/components
### Operating System
Ubuntu 20.04, windows 10
### Device
Hp Zbook G5
### Browser & Version
Chrome v8.0.4324.150, firefox v85.0.1
### Steps to reproduce
1. Open the material-kit-pro-react demo website.
2. Go to the components page.
3. Click one of the modals.
4. See the header and right dots jump.
### What is expected?
I expected the other UI components to stay still when toggling the modal.

### What is actually happening?
Currently, some elements are moved when the modal is opened and closed.

![modal_problem](https://user-images.githubusercontent.com/17570430/109124144-e0ef5a80-774a-11eb-8aa0-643171cbfb53.gif)

---
### Solution
I did not yet find a solution to this problem. It looks like it is related to the scrollbar. I tried the solutions in [this stackoverflow](https://stackoverflow.com/questions/45524214/how-do-i-stop-my-web-content-from-shifting-left-when-the-vertical-scrollbar-appe) post but they don't seem to work.

### Additional comments

Seems to be related to:
- https://github.com/mui-org/material-ui/issues/6656
- https://github.com/mui-org/material-ui/issues/10000
- https://github.com/mui-org/material-ui/issues/17353

**Comment by einazare** [comment]
Hello there, @rickstaa ,

Unfortunately, this cannot be solved.
It is because on Windows devices, the Scrollbar, when you open a modal, it disappears. And there is no way of solving this. It is the browser default behavior.

Best,
Manu

**Comment by rickstaa** [comment]
@EINazare I think your right. It seems to occur on Linux and Windows. I think if this is solvable it should be done in the material-UI repository. You can follow the related issue [here](https://github.com/mui-org/material-ui/issues/23489).

**Comment by rickstaa** [comment]
@EINazare Actually it seems they already fixed in Material-UI v5.

**Comment by Tetedeiench** [comment]
To anyone coming accross this issue, this is caused by the Dialog setting "overflow-y: hidden" when appearing on the body, which causes the scrollbar to disappear.

A fix for me was to set 'overflow-y':'auto !important' on the body element (CSS).

It's probably not the best fix, but it does the trick wonderfully for me !

**Comment by rickstaa** [comment]
@Tetedeiench Thanks a lot for uploading the fix. I'm glad that your solution worked out for you. Maybe I'm doing it wrong but for me, in the new chrome/firefox browsers, this, unfortunately, does not work. Adding the `overflow-y: auto !important` property adds extra padding for the scrollbar but still moves the elements.

![problem-overflow](https://user-images.githubusercontent.com/17570430/109411503-d62f0280-79a2-11eb-92a4-46a200542989.gif)

**Comment by Tetedeiench** [comment]
Hi @riskstaa,

Here's the problem reproduced on my (currently in dev) website : 
![scrollbar dialog issue](https://user-images.githubusercontent.com/23140774/109417437-fd49fc00-79c3-11eb-91f2-eda325c0379a.gif)

And with the fix i mentioned : 
![scrollbar dialog issue fixed](https://user-images.githubusercontent.com/23140774/109417456-0d61db80-79c4-11eb-93d6-f304d20bd047.gif)

I'm NOT an expert in frontend dev (quite the contrary), but the issue seems to be the dialog forcing overflow-y to hidden when appearing. 

This in turn hides the scrollbar if any was displayed before the dialog appeared, which moves the page behind the dialog to deal with this.

Of course, make sure you force overflow-y to any value you currently use with the dialog closed. I use auto personally !

I think in your case, looking at your CSS, **simply forcing "overflow: hidden !important"** will prevent the dialog from fiddling with it when appearing and things should go smooth. Also, make sure you're doing the change before opening the dialog, as changing this value when the dialog is opened will make things shake ;)

The fix is just making sure the scrollbar stays in place when the dialog is opened.

Edits : lots of spelling mistakes and clarifications, sorry.

**Comment by rickstaa** [comment]
@Tetedeiench Thanks a lot your solution seems to work. I thought I already tried it on the global CSS but I think I did something wrong the last time. I think it is a good workaround until material V5 is released.

**Comment by WROIATE** [comment]
> @Tetedeiench Thanks a lot for uploading the fix. I'm glad that your solution worked out for you. Maybe I'm doing it wrong but for me, in the new chrome/firefox browsers, this, unfortunately, does not work. Adding the `overflow-y: auto !important` property adds extra padding for the scrollbar but still moves the elements.

try add `padding-right: 0 !important` to `body` css
