### ISSUE TITLE
There is no possibility of starting from an empty project

### ISSUE THREAD

**Issue by lukaszswitaj** [creativetimofficial/ct-material-kit-pro-react#9]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

There should be possibility to start new application from scratch (empty project).

# Current Behavior

Now, the only way is to modify existing examples (great job, I admit), but it even dynamic routes must be modified.

# Failure Information (for bugs)

Not applicable.

## Steps to Reproduce

Try start new project from scratch and build web app using empty components.

## Context

Not applicable.

## Failure Logs

Not applicable.

**Comment by einazare** [comment]
Hello again @lukaszswitaj ,

I've actually started a new project and than added some of the components from this project to that one, and it was fairly easy to do so, only copy paste.
Yes, i'll admit that you need to copy and paste both the components and their dependencies (such as styles), and yes the routes are dynamically done, but i do not see this as an issue. Since you've already started a new app, you do not have to deal with our routes anymore, and the thing with the components, i believe it is something expected, since our product is not a library, if it were a library, yes it would be an issue.
I've added the **enhancement** label to this issue and i'll see how we could make our product better.
The only way i can think of, is that i would move the styles of the components together, but that would be quite hard to read, both the component code and it's styles.
Any guidance would be much appreciated. 

Best,
Manu

**Comment by farcaller** [comment]
Webpack's resolve/alias actually allows you to keep this mess together without copying it into ytour project, with a config similar to:

```
options: {
        '@materialkit': path.join(__dirname, 'thirdparty/material-kit-react-v1.3.0/src'),
        'assets': path.join(__dirname, 'thirdparty/material-kit-react-v1.3.0/src/assets'),
        'components': path.join(__dirname, 'thirdparty/material-kit-react-v1.3.0/src/components'),
      }
```

It'd be much better if material-kit-react was hermetic, only using relative imports within itself. Then it'd be a matter of `npm link`ing it and it could be used as a proper library.
