### ISSUE TITLE
[Bug] NPM install not working

### ISSUE THREAD

**Issue by jackrinhes** [creativetimofficial/ct-material-kit-pro-react#94]
### Version
latest
### Reproduction link
http://localhost
### Operating System
windows 10
### Device
PC
### Browser & Version
Chrome Versión 99.0.4844.82 (Build oficial) (64 bits)
### Steps to reproduce
NPM install
### What is expected?
compile
### What is actually happening?
not compiling
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @mui/material@5.2.0
npm ERR! Found: @emotion/react@11.4.1
npm ERR! node_modules/@emotion/react
npm ERR!   @emotion/react@"11.4.1" from the root project
npm ERR!   peer @emotion/react@"^11.0.0-rc.0" from @emotion/styled@11.3.0
npm ERR!   node_modules/@emotion/styled
npm ERR!     @emotion/styled@"11.3.0" from the root project
npm ERR!     peerOptional @emotion/styled@"^11.3.0" from @mui/material@5.2.0
npm ERR!     node_modules/@mui/material
npm ERR!       @mui/material@"5.2.0" from the root project
npm ERR!       1 more (@mui/icons-material)
npm ERR!     1 more (@mui/styled-engine)
npm ERR!   1 more (@mui/styled-engine)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @emotion/react@"^11.5.0" from @mui/material@5.2.0
npm ERR! node_modules/@mui/material
npm ERR!   @mui/material@"5.2.0" from the root project
npm ERR!   peer @mui/material@"^5.0.0" from @mui/icons-material@5.2.0
npm ERR!   node_modules/@mui/icons-material
npm ERR!     @mui/icons-material@"5.2.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @emotion/react@11.8.2
npm ERR! node_modules/@emotion/react
npm ERR!   peerOptional @emotion/react@"^11.5.0" from @mui/material@5.2.0
npm ERR!   node_modules/@mui/material
npm ERR!     @mui/material@"5.2.0" from the root project
npm ERR!     peer @mui/material@"^5.0.0" from @mui/icons-material@5.2.0
npm ERR!     node_modules/@mui/icons-material
npm ERR!       @mui/icons-material@"5.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

---

**Comment by sajadevo** [comment]
**Hi @jackrinhes**

Thanks for using our product, please use one of the following methods:
1. Run `npm i --legacy-peer-deps` instead of `npm install`
2. Or use yarn for install the dependencies of the product to install yarn just run `npm i -g yarn` and once its installed on the project root directory run the following command `yarn install`.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
